DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "test2",
  "number": 1111112
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": 2222
}